name: leilao_teste_dix
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - image/assets/icons/
    - image/imageNovilha/
    - image\degrade.png
    - image/logo.cadastro.png
    - image/Logo-dix_branca.png
    - image/background.logo.png
    - image/logo.apresentacao.png
    - image/Logo-dix_branca.png
    - image/appbar.png
    - image/avatar.png
    - image/assets/icons/vendaDireta.png
    - image/assets/icons/leiloes.png
    - image/assets/icons/resultados.png
    - image/assets/icons/settings.png
    - image/gadoCorte.png
    - image/assets/icons/TimeSquare.png
    - image\assets\icons\Location.png
    - image\leilaoGado.png
